FROM node:18-alpine

# Set working directory in container
WORKDIR /app

# Copy everything from your project into the container
COPY . .

# Expose the app port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]

